application: aproiowa
version: 1-004
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.5"

builtins:
- django_wsgi: on
- remote_api: on
- deferred: on
- appstats: on

handlers:
- url: /static
  static_dir: production_static
